// lib/src/graph_engine/graph.rs
use models::{
    edges::Edge,
    vertices::Vertex,
};
use std::collections::{HashMap, HashSet};
use uuid::Uuid;

/// In-memory graph structure used by the query / traversal engine.
pub struct Graph {
    /// `Vertex.id` is a `SerializableUuid`.  We store the raw `Uuid` for fast
    /// look-ups (the wrapper is just `pub struct SerializableUuid(pub Uuid)`).
    pub vertices: HashMap<Uuid, Vertex>,

    /// `Edge.id` is also a `Uuid` (generated by `Uuid::new_v4()` in the engine).
    pub edges: HashMap<Uuid, Edge>,

    // Fast adjacency look-ups
    pub adjacency_list: HashMap<Uuid, HashSet<Uuid>>, // from vertex id → set of edge ids
    pub inbound_list:   HashMap<Uuid, HashSet<Uuid>>, // to   vertex id → set of edge ids
}

impl Graph {
    /// Create an empty graph.
    pub fn new() -> Self {
        Self {
            vertices: HashMap::new(),
            edges: HashMap::new(),
            adjacency_list: HashMap::new(),
            inbound_list: HashMap::new(),
        }
    }

    /// Insert a vertex.  The vertex already carries its own `id`.
    pub fn add_vertex(&mut self, vertex: Vertex) {
        let id = vertex.id.0;               // `SerializableUuid` → `Uuid`
        self.vertices.insert(id, vertex);
    }

    /// Insert an edge and update the adjacency lists.
    pub fn add_edge(&mut self, edge: Edge) {
        let from = edge.outbound_id.0;      // ✅ Convert SerializableUuid → Uuid
        let to   = edge.inbound_id.0;       // ✅ Convert SerializableUuid → Uuid
        let edge_id = edge.id.0;            // ✅ Convert SerializableUuid → Uuid

        self.edges.insert(edge_id, edge);
        self.adjacency_list.entry(from).or_default().insert(edge_id);
        self.inbound_list.entry(to).or_default().insert(edge_id);
    }

    /// Retrieve a vertex by its `Uuid`.
    pub fn get_vertex(&self, id: &Uuid) -> Option<&Vertex> {
        self.vertices.get(id)
    }

    /// Outgoing edges from a vertex.
    pub fn get_edges_from(&self, vertex_id: &Uuid) -> Option<&HashSet<Uuid>> {
        self.adjacency_list.get(vertex_id)
    }

    /// Incoming edges to a vertex.
    pub fn get_edges_to(&self, vertex_id: &Uuid) -> Option<&HashSet<Uuid>> {
        self.inbound_list.get(vertex_id)
    }

    // -----------------------------------------------------------------
    // Add more engine-level helpers here (remove_vertex, remove_edge,
    // BFS/DFS, pattern-match integration, etc.)
    // -----------------------------------------------------------------
}