use chrono::{DateTime, Utc};
use uuid::Uuid;
use crate::constraints::PropertyConstraint;
use models::{Edge, ToEdge, FromEdge, Identifier, SerializableUuid, PropertyValue};
use models::properties::SerializableFloat; // <-- ADDED: Import for f64 wrapper
use crate::edges::relationship::EdgeSchema;

/// Represents a temporary flag indicating that two patient records are likely the same person,
/// generated by an automated Master Patient Index (MPI) matching workflow.
/// This link requires further confirmation (manual review or automated consensus).
///
/// Edge Label: HAS_POTENTIAL_DUPLICATE
/// Source Vertex: Patient A
/// Target Vertex: Patient B
#[derive(Debug, Clone)]
pub struct HasPotentialDuplicate {
    /// The unique identifier for this specific edge instance (String).
    pub id: String,
    
    /// ID of the source vertex (Patient A)
    pub source_id: Uuid,
    /// ID of the target vertex (Patient B)
    pub target_id: Uuid,

    /// The confidence score (0.0 to 1.0) calculated by the matching engine.
    pub confidence_score: f64,

    /// The name or version of the matching algorithm that identified the duplicate.
    pub algorithm_name: String,

    /// The date and time when the potential duplicate was flagged.
    pub match_date: DateTime<Utc>,
}

// --- EdgeSchema Implementation for declarative schema definition ---
impl EdgeSchema for HasPotentialDuplicate {
    fn edge_label() -> &'static str {
        "HAS_POTENTIAL_DUPLICATE"
    }

    fn property_constraints() -> Vec<PropertyConstraint> {
        vec![
            PropertyConstraint::new("id", true)
                .with_description("Unique edge instance ID (String)."),
            PropertyConstraint::new("confidence_score", true)
                .with_description("Probabilistic score (0.0 to 1.0) from the matching algorithm."),
            PropertyConstraint::new("algorithm_name", true)
                .with_description("The name/version of the MPI algorithm used for matching."),
            PropertyConstraint::new("match_date", true)
                .with_description("Timestamp when the potential duplicate was identified (RFC3339)."),
        ]
    }
}
// --- END EdgeSchema ---


// --- ToEdge Implementation: Struct -> Generic Edge (Serialization) ---
impl ToEdge for HasPotentialDuplicate {
    /// Converts the HasPotentialDuplicate struct into a generic Edge structure.
    fn to_edge(&self) -> Edge {
        let outbound_id: SerializableUuid = self.source_id.into();
        let inbound_id: SerializableUuid = self.target_id.into();
        let edge_label_identifier = Identifier::new(Self::edge_label().to_string())
            .expect("Invalid edge label identifier");

        let mut e = Edge::new(outbound_id, edge_label_identifier, inbound_id);

        // Add relationship-specific properties
        e = e.with_property(
            "id".to_string(), 
            PropertyValue::String(self.id.clone())
        );
        // FIX: Use SerializableFloat wrapper
        e = e.with_property(
            "confidence_score".to_string(), 
            PropertyValue::Float(SerializableFloat(self.confidence_score))
        );
        e = e.with_property(
            "algorithm_name".to_string(), 
            PropertyValue::String(self.algorithm_name.clone())
        );
        e = e.with_property(
            "match_date".to_string(), 
            PropertyValue::String(self.match_date.to_rfc3339()) // DateTime to RFC3339 String
        );

        e
    }
}


// --- FromEdge Implementation: Generic Edge -> Struct (Deserialization) ---
impl FromEdge for HasPotentialDuplicate {
    fn from_edge(edge: &Edge) -> Option<Self> {
        if edge.label.as_str() != Self::edge_label() { return None; }

        // Helper to parse RFC3339 string property into DateTime<Utc>
        let parse_datetime = |prop_name: &str, edge: &Edge| -> Option<DateTime<Utc>> {
            edge.properties.get(prop_name)
                .and_then(|v| v.as_str())
                .and_then(|s| chrono::DateTime::parse_from_rfc3339(s).ok())
                .map(|dt| dt.with_timezone(&chrono::Utc))
        };
        
        // 1. Convert IDs from SerializableUuid back to Uuid
        let source_id = Uuid::parse_str(&edge.outbound_id.to_string()).ok()?; 
        let target_id = Uuid::parse_str(&edge.inbound_id.to_string()).ok()?;

        // 2. Safely extract mandatory properties
        let confidence_score = match edge.properties.get("confidence_score")? {
            // FIX: Pattern match to extract the inner f64 from SerializableFloat
            PropertyValue::Float(sf) => sf.0, 
            _ => return None,
        };
        
        Some(HasPotentialDuplicate {
            id: edge.properties.get("id")?.as_str()?.to_string(),
            source_id, 
            target_id,
            confidence_score,
            algorithm_name: edge.properties.get("algorithm_name")?.as_str()?.to_string(),
            match_date: parse_datetime("match_date", edge)?,
        })
    }
}
